config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  resources :todos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todos_params)

    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update(todos_params)
      redirect_to todos_path
    else
      render :edit
    end
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to todos_path
  end

end

private

  def todos_params
    params.require(:todo).permit(:title, :body)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="nav nav-wrapper black">
<a class="btn-floating btn-large pulse"
<%= link_to 'Home', root_path %>
<a class="btn-floating btn-large pulse"
<%= link_to 'About', about_path %>
<ul class="right">
<a class="btn-floating btn-large pulse"
<%= link_to 'View', todos_path %>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="center blue darken-1">TodoList</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body background="http://www.baltana.com/files/wallpapers-4/Parchment-Background-Best-Wallpaper-14476.png">
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>Basically you're creating a todo list. Simple enough. Just click on the buttons and do as it says...</p>
<%= link_to 'Back to Home', root_path %>

app/views/static_pages/home.html.erb
<h1>Make your own To-do List</h1>
<p>
  Here you can see your <%= link_to 'To-do list', todos_path %>
</p>
<p>
  Or to find out more information about the page, <%= link_to 'Click Here.', about_path %>
</p>

app/views/todos/edit.html.erb
<h1>Edit Todo Item</h1>
<%=  form_for @todo do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br  />
<%= f.label :body %>
<%= f.text_field :body %>
<br  />
<%= f.submit %>
<% end %>

app/views/todos/index.html.erb
<h1>Todos List</h1>
<%= link_to 'New Item', new_todo_path %>
<% @todos.each do |todo| %>
  <h2><%= todo.title %></h2>
  <a class="btn"<%= link_to 'Show Item', todo_path(todo) %>
  <a class="btn"<%= link_to 'Edit Item', edit_todo_path(todo) %>
  <a class="btn"<%= link_to 'Completed Task', todo, method: :delete %>
  <% end %>

app/views/todos/new.html.erb
<h1>New Todo</h1>
<%=  form_for @todo do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br  />
<%= f.label :body %>
<%= f.text_field :body %>
<br  />
<%= f.submit %>
<% end %>

app/views/todos/show.html.erb
<h1><%= @todo.title %> </h1>
<h4><%= @todo.body %></h4>
<%= link_to 'Back', todos_path %>